sudo: false
language: node_js
node_js:
  - '8'
  - '6'

before_script:
  - 'if [ "$NODE6" = "true" ]; then npm build --cwd node_modules/puppeteer; fi'

addons:
  apt:
    packages:
      # This is required to run puppeteer (chrome) on linux/trusty
      - libnss3
